function data = generate(width,res,model,param)
% QRS.FIELDS.GAUSSIAN.GENERATE generate gaussian random field using R
%   F = QRS.FIELDS.GAUSSIAN.GENERATE(N,RES,MODEL,PARAM) returns a 2D matrix of
%   size N/RES containing a 2D Gaussian random field generated by R. The
%   points in the field are related according to the string MODEL and the
%   vector PARAM, which are used according to the documentation for GaussRF in
%   the R Package RandomFields.
%
%   http://www.inside-r.org/packages/cran/RandomFields/docs/GaussRF

paramstr = num2str(param,'%f ');

% give R a temporary filename to which it can write data
[pn,~,~] = fileparts(mfilename('fullpath'));
fn = tempname;
qrs.r.exec([pn filesep 'generate.R'],'%s %s %d %f %s',fn,model,width,res,paramstr);

% retrieve data written by R
f = load(fn,'-mat','data');
delete(fn);

data = f.data;