#!/bin/bash

if [ $# -ne 2 ]; then
    echo "Usage: run-example approach Strategy      \
                   approach: [kriging mutualInfo]       \
                   Strategy: [greedy ACO sample random]" >&2
    exit 2
fi


JOB_NAME_PATTERN="$2_\$SUB_NAME"
DATA_DIR_PATTERN="./data/\$JOB_NAME"

FIELD_MODEL="spherical"
NUM_RUNS=500

    	SUB_NAME="short_range"
    	eval JOB_NAME=$JOB_NAME_PATTERN
    	eval DATA_DIR=$DATA_DIR_PATTERN
    	JOB_ID=$( ./qjob -N "$JOB_NAME" -t 1-$NUM_RUNS ./scripts/qrs.sub \
    		"'Cluster',true,"               \
    		"'DataDirectory','$DATA_DIR',"  \
    		"'FieldRange',20,"              \
    		"'Algorithm','$1',"		\
    		"'Strategy','$2',"		    \
		"'FieldModel','$FIELD_MODEL'"  )
        ./qclean $JOB_ID "$DATA_DIR" > /dev/null


    	SUB_NAME="medium_range"
    	eval JOB_NAME=$JOB_NAME_PATTERN
    	eval DATA_DIR=$DATA_DIR_PATTERN
    	JOB_ID=$( ./qjob -N "$JOB_NAME" -t 1-$NUM_RUNS ./scripts/qrs.sub \
    		"'Cluster',true,"               \
    		"'DataDirectory','$DATA_DIR',"  \
    		"'FieldRange',40,"              \
    		"'Algorithm','$1',"		\
    		"'Strategy','$2',"		    \
    		"'FieldModel','$FIELD_MODEL'"  )
        ./qclean $JOB_ID "$DATA_DIR" > /dev/null


    	SUB_NAME="long_range"
    	eval JOB_NAME=$JOB_NAME_PATTERN
    	eval DATA_DIR=$DATA_DIR_PATTERN
    	JOB_ID=$( ./qjob -N "$JOB_NAME" -t 1-$NUM_RUNS ./scripts/qrs.sub \
    		"'Cluster',true,"               \
    		"'DataDirectory','$DATA_DIR',"  \
    		"'FieldRange',50,"              \
    		"'Algorithm','$1',"		\
    		"'Strategy','$2',"		    \
    		"'FieldModel','$FIELD_MODEL'"  )
        ./qclean $JOB_ID "$DATA_DIR" > /dev/null
