#!/bin/bash

if [ $# -ne 1 ]; then
	echo "Usage: run-example name" >&2
	exit 2
fi

JOB_NAME_PATTERN="$1_\$SUB_NAME"
DATA_DIR_PATTERN="./data/\$JOB_NAME"

FIELD_MODEL='spherical'
NUM_RUNS=10

SUB_NAME="qrs-short-range"
eval JOB_NAME=$JOB_NAME_PATTERN
eval DATA_DIR=$DATA_DIR_PATTERN
JOB_ID=$( ./qjob -N "$JOB_NAME" -t 1-$NUM_RUNS ./scripts/qrs.sub \
	"'Cluster',true,"              \
	"'DataDirectory','$DATA_DIR'," \
	"'FieldRange',20,"             \
	"'FieldModel','$FIELD_MODEL'"  )
./qclean $JOB_ID "$DATA_DIR.txt" "$DATA_DIR" > /dev/null

SUB_NAME="qrs-medium-range"
eval JOB_NAME=$JOB_NAME_PATTERN
eval DATA_DIR=$DATA_DIR_PATTERN
JOB_ID=$( ./qjob -N "$JOB_NAME" -t 1-$NUM_RUNS ./scripts/qrs.sub \
	"'Cluster',true,"              \
	"'DataDirectory','$DATA_DIR'," \
	"'FieldRange',30,"             \
	"'FieldModel','$FIELD_MODEL'"  )
./qclean $JOB_ID "$DATA_DIR.txt" "$DATA_DIR" > /dev/null

SUB_NAME="qrs-long-range"
eval JOB_NAME=$JOB_NAME_PATTERN
eval DATA_DIR=$DATA_DIR_PATTERN
JOB_ID=$( ./qjob -N "$JOB_NAME" -t 1-$NUM_RUNS ./scripts/qrs.sub \
	"'Cluster',true,"              \
	"'DataDirectory','$DATA_DIR'," \
	"'FieldRange',40,"             \
	"'FieldModel','$FIELD_MODEL'"  )
./qclean $JOB_ID "$DATA_DIR.txt" "$DATA_DIR" > /dev/null
