#!/bin/bash

JOB_NAME_PATTERN="\$SUB_NAME"
DATA_DIR_PATTERN="./data/\$JOB_NAME"

FIELD_MODEL="gauss"
STRATEGY=('greedy' 'ACO')
ALGORITHM=('kriging' 'mutualInfo')

NUM_RUNS=200
for i in "${STRATEGY[@]}"
do
    for j in "${ALGORITHM[@]}"
    do

        for k in 20 40 50 100
        do
    	   SUB_NAME="${i}_${j}_${k}"
    	   eval JOB_NAME=$JOB_NAME_PATTERN
    	   eval DATA_DIR=$DATA_DIR_PATTERN
    	   JOB_ID=$( ./qjob -N "$JOB_NAME" -t 1-$NUM_RUNS ./scripts/qrs.sub \
    		  "'Cluster',true,"               \
    		  "'DataDirectory','$DATA_DIR',"  \
    		  "'FieldRange',$k,"              \
    		  "'Algorithm','$j',"		\
    		  "'Strategy','$i',"		    \
		      "'FieldModel','$FIELD_MODEL'"  )
            ./qclean $JOB_ID "$DATA_DIR" > /dev/null

done

done
done