#!/bin/bash

JOB_NAME_PATTERN="\$SUB_NAME"
DATA_DIR_PATTERN="./data/\$JOB_NAME"

FIELD_MODEL="gauss"
STRATEGY=('greedy' 'sample')
ALGORITHM=('kriging' 'mutualInfo')
FUNCTION=('linear' 'spherical' 'quadratic' 'cubic')
NUM_RUNS=100

for strategy in "${STRATEGY[@]}"
do
    for alg in "${ALGORITHM[@]}"
    do
            for range in 5 20 50 150 300
            do
                if [ ${alg} == 'mutualInfo' ]
                    then
                    for varFunc in "${FUNCTION[@]}"
                    do
                        SUB_NAME="${alg}_${strategy}_${varFunc}_${range}"
                        eval JOB_NAME=$JOB_NAME_PATTERN
                        eval DATA_DIR=$DATA_DIR_PATTERN
                        JOB_ID=$( ./qjob -N "$JOB_NAME" -t 1-$NUM_RUNS ./scripts/qrs.sub \
                            "'DataDirectory','$DATA_DIR',"  \
                            "'FieldRange',$range,"              \
                            "'Algorithm','$alg',"		\
                            "'Strategy','$strategy',"		    \
                            "'Function','$varFunc',"            \
                            "'Estimation',0,"            \
                            "'Range',$(($range / 4)),"            \
                            "'Sill',25,"            \
                            "'Function','$varFunc',"            \
                            "'FieldModel','$FIELD_MODEL'"  )
                        ./qclean $JOB_ID "$DATA_DIR" > /dev/null
                    done
                else
                    SUB_NAME="${alg}_${strategy}_${range}"
                    eval JOB_NAME=$JOB_NAME_PATTERN
                    eval DATA_DIR=$DATA_DIR_PATTERN
                    JOB_ID=$( ./qjob -N "$JOB_NAME" -t 1-$NUM_RUNS ./scripts/qrs.sub \
                        "'DataDirectory','$DATA_DIR',"  \
                        "'FieldRange',$range,"              \
                        "'Algorithm','$alg',"       \
                        "'Strategy','$strategy',"            \
                        "'Estimation',0,"            \
                        "'Range',$(($range / 4)),"            \
                        "'Sill',25,"            \
                        "'FieldModel','$FIELD_MODEL'"  )
                    ./qclean $JOB_ID "$DATA_DIR" > /dev/null
                fi
            done
    done
done