#!/bin/bash

JOB_NAME_PATTERN="\$SUB_NAME"
DATA_DIR_PATTERN="./data/\$JOB_NAME"

FIELD_MODEL="spherical"
STRATEGY=('greedy' 'ACO' 'sample' 'random')
ALGORITHM=('kriging' 'mutualInfo')
FUNCTION=('linear' 'spherical' 'quadratic' 'cubic')
NUM_RUNS=200

for strategy in "${STRATEGY[@]}"
do
    if [ ${strategy} != 'random' ]
    then
    for alg in "${ALGORITHM[@]}"
    do
        for numDirections in 8 16
        do
            for range in 20 40 50 100 150
            do
                if [ ${alg} == 'mutualInfo' ]
                    then
                    for varFunc in "${FUNCTION[@]}"
                    do
                        SUB_NAME="${alg}_${strategy}_${varFunc}_${numDirections}_${range}"
                        eval JOB_NAME=$JOB_NAME_PATTERN
                        eval DATA_DIR=$DATA_DIR_PATTERN
                        JOB_ID=$( ./qjob -N "$JOB_NAME" -t 1-$NUM_RUNS ./scripts/qrs.sub \
                            "'DataDirectory','$DATA_DIR',"  \
                            "'FieldRange',$range,"              \
                            "'Algorithm','$alg',"		\
                            "'Strategy','$strategy',"		    \
                            "'Function','$varFunc',"            \
                            "'AllowedDirections',$numDirections,"            \
                            "'FieldModel','$FIELD_MODEL'"  )
                        ./qclean $JOB_ID "$DATA_DIR" > /dev/null
                    done
                else
                    SUB_NAME="${alg}_${strategy}_${numDirections}_${range}"
                    eval JOB_NAME=$JOB_NAME_PATTERN
                    eval DATA_DIR=$DATA_DIR_PATTERN
                    JOB_ID=$( ./qjob -N "$JOB_NAME" -t 1-$NUM_RUNS ./scripts/qrs.sub \
                        "'DataDirectory','$DATA_DIR',"  \
                        "'FieldRange',$range,"              \
                        "'Algorithm','$alg',"       \
                        "'Strategy','$strategy',"            \
                        "'AllowedDirections',$numDirections,"            \
                        "'FieldModel','$FIELD_MODEL'"  )
                    ./qclean $JOB_ID "$DATA_DIR" > /dev/null
                fi
            done
        done
    done
    else
        for range in 20 40 50 100 150
            do
            SUB_NAME="${strategy}_${range}"
            eval JOB_NAME=$JOB_NAME_PATTERN
            eval DATA_DIR=$DATA_DIR_PATTERN
            JOB_ID=$( ./qjob -N "$JOB_NAME" -t 1-$NUM_RUNS ./scripts/qrs.sub \
                "'DataDirectory','$DATA_DIR',"  \
                "'FieldRange',$range,"              \
                "'Strategy','$strategy',"            \
                "'FieldModel','$FIELD_MODEL'"  )
            ./qclean $JOB_ID "$DATA_DIR" > /dev/null
        done
    fi
done